#!/usr/bin/env tsx
// Bulk auto-apply HIGH-confidence tag suggestions into notes.tags.
//
// User decision (D-013): for every tag_suggestions row with confidence='high'
// AND applied_at IS NULL, merge the full suggested_tags array (primary +
// secondaries) into notes.tags as the union (dedup'd), then mark applied.
//
// Medium/low rows are left untouched here — those surface as ghost pills in
// the UI and require an explicit user accept.
//
// Backed by golden-50 calibration: primary_hit_rate = 1.00 on the 28
// high-confidence notes in the eval sample. Tag-set precision is 0.87, so
// ~13% of *secondary* tags applied this way will be wrong — accepted
// tradeoff; fixup is via deletion.
//
// Usage:
//   # local (default):
//   tsx scripts/auto-apply-high-conf.ts > db/seed.auto-apply-high.sql 2> /tmp/apply.err
//   wrangler d1 execute board-db --local --file=db/seed.auto-apply-high.sql
//
//   # remote (prod backfill):
//   tsx scripts/auto-apply-high-conf.ts --remote > db/seed.auto-apply-high.sql
//   wrangler d1 execute board-db --remote --file=db/seed.auto-apply-high.sql
//
// Idempotent: re-running is a no-op because applied_at IS NOT NULL filters
// out already-applied rows (state lives per-DB — local and remote each have
// their own applied_at column, so they track independently).
//
// D1 compatibility: emitted SQL deliberately omits BEGIN TRANSACTION/COMMIT.
// `wrangler d1 execute --file` auto-batches statements and rejects explicit
// transactions ("please use state.storage.transaction()..."). Atomicity on
// remote is at the per-statement level; full-batch atomicity comes from
// wrangler's batch wrapper.

import { execSync } from 'node:child_process';

type Row = { uuid: string; note_tags: string; sugg_tags: string };
type WranglerResult = [{ success: boolean; results: Row[]; meta?: unknown }];

function sqlQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

const useRemote = process.argv.includes('--remote');
const dbFlag = useRemote ? '--remote' : '--local';

// Pull every high-conf pending suggestion joined with its note. We need the
// existing tags array so we can compute the merged union in TS (SQLite has
// json_each but the UPDATE-FROM ergonomics are awkward; doing the merge here
// keeps the SQL flat and idempotent).
const queryResult = execSync(
  `npx wrangler d1 execute board-db ${dbFlag} --json --command ` +
  `"SELECT n.uuid as uuid, n.tags as note_tags, ts.suggested_tags as sugg_tags ` +
  `  FROM notes n ` +
  `  JOIN tag_suggestions ts ON ts.uuid = n.uuid ` +
  `  WHERE ts.confidence = 'high' AND ts.applied_at IS NULL"`,
  { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
);

const parsed = JSON.parse(queryResult) as WranglerResult;
const rows = parsed[0]?.results ?? [];

const now = Date.now();
let considered = 0;
let tagUpdates = 0;          // rows where notes.tags actually changes
let dedupSkips = 0;          // rows where every suggested tag was already present
let totalAdditions = 0;      // total individual tags added across all notes

process.stdout.write(`-- Generated by scripts/auto-apply-high-conf.ts on ${new Date().toISOString()}\n`);
process.stdout.write(`-- Source DB: ${dbFlag}\n`);
process.stdout.write(`-- Bulk-applying ${rows.length} high-confidence pending suggestions.\n`);
process.stdout.write(`-- Strategy: union notes.tags ∪ tag_suggestions.suggested_tags, dedup, write back.\n`);
process.stdout.write(`-- No BEGIN/COMMIT: D1 wrangler batches the file and rejects explicit transactions.\n\n`);

for (const r of rows) {
  considered++;
  const existing: string[] = JSON.parse(r.note_tags || '[]');
  const suggested: string[] = JSON.parse(r.sugg_tags || '[]');

  // Preserve order of existing tags; append new ones in suggested order.
  // The first tag in notes.tags drives the bg color (via TAG_BG), so if the
  // note already has a manual tag we don't reorder around it.
  const seen = new Set(existing);
  const additions: string[] = [];
  for (const t of suggested) {
    if (!seen.has(t)) {
      seen.add(t);
      additions.push(t);
    }
  }

  if (additions.length === 0) {
    dedupSkips++;
  } else {
    const merged = [...existing, ...additions];
    totalAdditions += additions.length;
    tagUpdates++;
    process.stdout.write(
      `UPDATE notes SET tags = ${sqlQuote(JSON.stringify(merged))} ` +
      `WHERE uuid = ${sqlQuote(r.uuid)};\n`,
    );
  }
  // Always mark applied — even dedup-skips count as "user has accepted".
  process.stdout.write(
    `UPDATE tag_suggestions SET applied_at = ${now} ` +
    `WHERE uuid = ${sqlQuote(r.uuid)};\n`,
  );
}

process.stderr.write(`[auto-apply] source DB : ${dbFlag}\n`);
process.stderr.write(`[auto-apply] considered : ${considered} high-conf pending rows\n`);
process.stderr.write(`[auto-apply] tag-updates: ${tagUpdates} notes.tags rows modified\n`);
process.stderr.write(`[auto-apply] dedup-skips: ${dedupSkips} suggestions already covered by existing tags\n`);
process.stderr.write(`[auto-apply] additions  : ${totalAdditions} individual tags added\n`);
process.stderr.write(`[auto-apply] all ${considered} suggestions marked applied_at=${now}\n`);
