#!/usr/bin/env tsx
// One-shot exporter: walks Apple Notes via JXA (osascript -l JavaScript) and
// writes a stream of INSERT OR IGNORE statements to stdout. Pipe into a file
// and run via wrangler:
//
//   tsx scripts/export-apple-notes.ts > db/seed.apple.sql
//   wrangler d1 execute board-db --local  --file=db/seed.apple.sql
//   wrangler d1 execute board-db --remote --file=db/seed.apple.sql
//
// Or just use the npm wrappers:
//   npm run notes:apple:local
//   npm run notes:apple:remote
//
// uuid PK: freshly generated short-uuid per row (same scheme the API uses).
// dedup:   UNIQUE(content_hash) on the schema — sha256(normalized text) makes
//          re-runs and cross-source imports (newnotes vs apple) collapse to
//          the same row via INSERT OR IGNORE. See D-009 + content-hash.ts.
//
// First run will trigger a macOS prompt asking the calling terminal for
// permission to control Notes. Grant once; subsequent runs are silent.

import { spawnSync } from 'node:child_process';

import short from 'short-uuid';

import { contentHash } from './lib/content-hash';
import { parseHashtags, stripFirstHashtagsForTags } from './lib/legacy-hashtag-parser';

const translator = short();

// JXA script. Uses *collection-form* getters to pull each property in one
// Apple-event round trip rather than iterating note-by-note (~100× faster on
// libraries of any real size).
const JXA = `
(() => {
  const Notes = Application('Notes');
  const ids        = Notes.notes.id();
  const names      = Notes.notes.name();
  const bodies     = Notes.notes.plaintext();
  const created    = Notes.notes.creationDate();
  const modified   = Notes.notes.modificationDate();
  const out = [];
  for (let i = 0; i < ids.length; i++) {
    out.push({
      id:       String(ids[i]),
      name:     String(names[i]    == null ? '' : names[i]),
      text:     String(bodies[i]   == null ? '' : bodies[i]),
      created:  +new Date(created[i]),
      modified: +new Date(modified[i]),
    });
  }
  return JSON.stringify(out);
})();
`;

const proc = spawnSync('osascript', ['-l', 'JavaScript', '-e', JXA], {
  encoding: 'utf8',
  maxBuffer: 256 * 1024 * 1024, // big libraries can serialize to >50 MB
});

if (proc.status !== 0) {
  process.stderr.write(`[apple-notes] osascript failed (status ${proc.status})\n`);
  if (proc.stderr) process.stderr.write(proc.stderr.trim() + '\n');
  process.stderr.write(
    `Hint: System Settings → Privacy & Security → Automation — grant your terminal permission to control Notes, then retry.\n`,
  );
  process.exit(1);
}

type Note = {
  id:       string;
  name:     string;
  text:     string;
  created:  number;
  modified: number;
};

let notes: Note[];
try {
  notes = JSON.parse(proc.stdout) as Note[];
} catch (err) {
  process.stderr.write(`[apple-notes] could not parse JXA output: ${String(err)}\n`);
  process.exit(1);
}

function sqlQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

function composeBody(title: string, text: string): string {
  const t = title.trim();
  const body = text.replace(/\r\n/g, '\n').trimEnd();
  const firstLine = (body.split('\n', 1)[0] ?? '').trim();
  // Apple synthesizes the title from line 1 by default — skip duplication.
  if (!t || firstLine === t) return body;
  return `${t}\n\n${body}`;
}

process.stdout.write(`-- Generated by scripts/export-apple-notes.ts on ${new Date().toISOString()}\n`);
process.stdout.write(`-- ${notes.length} notes from Apple Notes (via JXA)\n`);
process.stdout.write(`-- Idempotent: INSERT OR IGNORE on UNIQUE(content_hash)\n\n`);

let written = 0;
let skipped = 0;

for (const n of notes) {
  if (!n.id) { skipped++; continue; }

  const text = composeBody(n.name ?? '', n.text ?? '');
  if (text.trim().length === 0) { skipped++; continue; }

  // Hard cap mirrors the POST /api/notes server-side cap (50k chars).
  const capped = text.slice(0, 50_000);

  // Tag standalone (2026-06-02): derive tags from legacy hashtags + strip
  // the first inline occurrence from the imported body.
  const derived   = parseHashtags(capped);
  const cleanText = stripFirstHashtagsForTags(capped, derived);
  const tags      = JSON.stringify(derived);
  const createdAt = Number.isFinite(n.created)  ? n.created  : Date.now();
  const updatedAt = Number.isFinite(n.modified) ? n.modified : createdAt;
  const uuid      = translator.new();
  const hash      = contentHash(cleanText);

  process.stdout.write(
    `INSERT OR IGNORE INTO notes (uuid, text, tags, color, z_index, created_at, updated_at, tags_updated_at, content_hash) VALUES (` +
    `${sqlQuote(uuid)}, ` +
    `${sqlQuote(cleanText)}, ` +
    `${sqlQuote(tags)}, ` +
    `NULL, 0, ${createdAt}, ${updatedAt}, ${updatedAt}, ` +
    `${sqlQuote(hash)});\n`,
  );
  written++;
}

process.stderr.write(`[apple-notes] wrote ${written}, skipped ${skipped}\n`);
