#!/usr/bin/env tsx
// One-shot importer: reads /Users/anishthite/workspace/log/newnotes.json (Mongo
// export) and writes a stream of INSERT statements to stdout. Pipe into a file
// and run via:
//   tsx scripts/import-newnotes.ts > db/seed.sql
//   wrangler d1 execute board-db --local --file=db/seed.sql
//
// uuid PK: freshly generated short-uuid per row (same scheme the API uses).
// dedup:   UNIQUE(content_hash) on the schema — sha256(normalized text) makes
//          re-runs and cross-source imports collapse to the same row via
//          INSERT OR IGNORE. See D-009 + scripts/lib/content-hash.ts.

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import short from 'short-uuid';

import { contentHash } from './lib/content-hash';
import { parseHashtags, stripFirstHashtagsForTags } from './lib/legacy-hashtag-parser';

const translator = short();

// Resolve newnotes.json:
//   1. $NEWNOTES_PATH (explicit override)
//   2. <repo>/newnotes.json           — self-contained layout (default after the
//                                       extract-to-own-repo move)
//   3. <repo>/../newnotes.json        — legacy layout (when board/ was a
//                                       subdir of log/, newnotes.json sat alongside)
function findNewnotesSource(here: string): string {
  const fromEnv = process.env.NEWNOTES_PATH;
  if (fromEnv) {
    if (!existsSync(fromEnv)) {
      throw new Error(`NEWNOTES_PATH=${fromEnv} but file does not exist`);
    }
    return fromEnv;
  }
  for (const candidate of [
    resolve(here, '../newnotes.json'),     // repo root
    resolve(here, '../../newnotes.json'),  // legacy parent
  ]) {
    if (existsSync(candidate)) return candidate;
  }
  throw new Error(
    'newnotes.json not found. Place it at the repo root or set NEWNOTES_PATH=/abs/path.',
  );
}

type MongoOid = { $oid: string };
type MongoDate = { $date: { $numberLong: string } };
type MongoNote = {
  _id: MongoOid;
  uuid: string;
  title: string;
  text: string;
  updated: MongoDate;
  link?: string;
};

// Resolve relative to this script so paths work from anywhere.
const HERE = new URL('.', import.meta.url).pathname;
const SOURCE = findNewnotesSource(HERE);

const raw = readFileSync(SOURCE, 'utf8');
const notes = JSON.parse(raw) as MongoNote[];

function sqlQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

process.stdout.write(`-- Generated by scripts/import-newnotes.ts on ${new Date().toISOString()}\n`);
process.stdout.write(`-- ${notes.length} notes from newnotes.json\n`);
process.stdout.write(`-- Idempotent: INSERT OR IGNORE on UNIQUE(content_hash)\n\n`);

let written = 0;
let skipped = 0;

for (const n of notes) {
  // Skip rows with no text body (the source has a few of these).
  if (!n.text || n.text.trim().length === 0) { skipped++; continue; }

  // Tag standalone (2026-06-02): derive tags from legacy hashtags, then
  // strip the first inline occurrence so the imported body is clean.
  const rawText = n.text;
  const derived = parseHashtags(rawText);
  const cleanText = stripFirstHashtagsForTags(rawText, derived);
  const tags = JSON.stringify(derived);
  // Mongo's $date.$numberLong is epoch ms as a string.
  const updated = Number(n.updated?.$date?.$numberLong ?? Date.now());
  const uuid = translator.new();
  const hash = contentHash(cleanText);

  process.stdout.write(
    `INSERT OR IGNORE INTO notes (uuid, text, tags, color, z_index, created_at, updated_at, tags_updated_at, content_hash) VALUES (` +
    `${sqlQuote(uuid)}, ` +
    `${sqlQuote(cleanText)}, ` +
    `${sqlQuote(tags)}, ` +
    `NULL, 0, ${updated}, ${updated}, ${updated}, ` +
    `${sqlQuote(hash)});\n`,
  );
  written++;
}

process.stderr.write(`[import] wrote ${written}, skipped ${skipped}\n`);
