#!/usr/bin/env tsx
// Round-3 loader: reads db/round3/tag-suggestions-final-r3.jsonl and emits
// SQL that populates the tag_suggestions table on remote D1.
//
//   tsx scripts/load-suggestions-r3.ts > db/round3/seed.suggestions-r3.sql
//   wrangler d1 execute board-db --remote --file=db/round3/seed.suggestions-r3.sql
//
// ───────────────────────────────────────────────────────────────────────
// Why this isn't load-suggestions.ts:
//
//   The round-2 loader joins via `content_hash` because round-2 notes
//   originated in newnotes.json (with Mongo source uuids) and the importer
//   minted fresh D1 uuids. round-3 notes were created directly via the API
//   into D1 — their uuids in db/round3/untagged-notes.jsonl ARE the D1
//   uuids. No translation needed; emit straight VALUES-form INSERTs.
//
//   D1 wrangler --file rejects explicit transactions, so no BEGIN/COMMIT.
//   Each INSERT OR REPLACE is its own statement; the file-batch wraps them.

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

type FinalRow = {
  uuid: string;
  suggested_tags: string[];
  primary: string;
  proposed_tag: string | null;
  confidence: 'high' | 'medium' | 'low';
  rationale: string;
};

const REPO = resolve(__dirname, '..');
const FINAL = resolve(REPO, 'db/round3/tag-suggestions-final-r3.jsonl');

function sqlQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

const now = Math.floor(Date.now() / 1000);

process.stdout.write(
  `-- Generated by scripts/load-suggestions-r3.ts on ${new Date().toISOString()}\n`,
);
process.stdout.write(
  `-- Source: db/round3/tag-suggestions-final-r3.jsonl (D1-uuid keyed; no content_hash join)\n`,
);
process.stdout.write(
  `-- Idempotent: INSERT OR REPLACE keyed on uuid (PK).\n`,
);
process.stdout.write(
  `-- No BEGIN/COMMIT: D1 wrangler --file auto-batches and rejects explicit transactions.\n\n`,
);

let emitted = 0;
const lines = readFileSync(FINAL, 'utf8').split('\n');
for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed) continue;
  const r = JSON.parse(trimmed) as FinalRow;

  const suggestedTagsJson = JSON.stringify(r.suggested_tags);
  const rationale = r.rationale ?? '';

  // VALUES-form INSERT: uuid already exists in notes (FK satisfied by
  // construction — these uuids came from `SELECT n.uuid FROM notes n` on prod).
  process.stdout.write(
    `INSERT OR REPLACE INTO tag_suggestions ` +
      `(uuid, suggested_tags, primary_tag, confidence, rationale, applied_at, created_at) ` +
      `VALUES (` +
      `${sqlQuote(r.uuid)}, ` +
      `${sqlQuote(suggestedTagsJson)}, ` +
      `${sqlQuote(r.primary)}, ` +
      `${sqlQuote(r.confidence)}, ` +
      `${sqlQuote(rationale)}, ` +
      `NULL, ` +
      `${now}` +
      `);\n`,
  );
  emitted++;
}

process.stderr.write(
  `[load-suggestions-r3] emitted ${emitted} INSERT statements\n`,
);
