#!/usr/bin/env tsx
// One-shot loader: reads db/tag-suggestions-final.jsonl and emits SQL that
// populates the tag_suggestions table. Mirrors scripts/import-newnotes.ts.
//
//   tsx scripts/load-suggestions.ts > db/seed.suggestions.sql
//   wrangler d1 execute board-db --local --file=db/seed.suggestions.sql
//
// ───────────────────────────────────────────────────────────────────────
// Why this isn't a plain INSERT VALUES (...):
//
//   scripts/import-newnotes.ts:81 mints a FRESH short-uuid per row
//   (`translator.new()`). The Mongo source uuid is discarded. So the uuid
//   in tag-suggestions-final.jsonl (which came from newnotes.json[i].uuid,
//   propagated through the chunking pipeline) does **not** match
//   notes.uuid in D1. Verified empirically: 0/3 sample uuids found.
//
//   The only stable cross-source key is `content_hash` (sha256-prefix of
//   normalized text, populated by import-newnotes.ts and enforced UNIQUE
//   on notes.content_hash; see scripts/lib/content-hash.ts).
//
//   Strategy:
//     1. Build sourceUuid → text map from newnotes.json.
//     2. For each final.jsonl row, look up text by sourceUuid → compute
//        contentHash(text).
//     3. Emit `INSERT OR REPLACE ... SELECT n.uuid, <literals> FROM notes n
//        WHERE n.content_hash = '<hash>'`. SELECT-form INSERT natively
//        skips when no notes row matches, so FK violations are impossible.
// ───────────────────────────────────────────────────────────────────────

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { contentHash } from './lib/content-hash';

type FinalRow = {
  uuid: string;                          // SOURCE uuid (from newnotes.json), NOT notes.uuid
  suggested_tags: string[];
  primary: string;
  proposed_tag: string | null;           // always null post-promotion; ignored here
  confidence: 'high' | 'medium' | 'low';
  rationale: string;
};

type MongoOid  = { $oid: string };
type MongoDate = { $date: { $numberLong: string } };
type MongoNote = {
  _id: MongoOid;
  uuid: string;
  title: string;
  text: string;
  updated: MongoDate;
  link?: string;
};

const HERE = new URL('.', import.meta.url).pathname;

function findFile(here: string, name: string, envVar?: string): string {
  if (envVar && process.env[envVar]) {
    const p = process.env[envVar]!;
    if (!existsSync(p)) throw new Error(`${envVar}=${p} but file does not exist`);
    return p;
  }
  for (const candidate of [
    resolve(here, '..', name),
    resolve(here, '../..', name),
  ]) {
    if (existsSync(candidate)) return candidate;
  }
  throw new Error(`${name} not found at repo root or one level up.`);
}

const FINAL    = findFile(HERE, 'db/tag-suggestions-final.jsonl');
const NEWNOTES = findFile(HERE, 'newnotes.json', 'NEWNOTES_PATH');

// Build sourceUuid → text map so we can look up the original text for each
// row in tag-suggestions-final.jsonl. Note: parts of the corpus may have
// duplicate text under different Mongo uuids — the content_hash collapses
// them into one notes row, which is exactly what we want for tag suggestions
// (one note, one suggestion). INSERT OR REPLACE handles the collapse.
const mongoNotes = JSON.parse(readFileSync(NEWNOTES, 'utf8')) as MongoNote[];
const textBySourceUuid = new Map<string, string>();
for (const n of mongoNotes) {
  if (n.text && n.text.trim().length > 0) {
    textBySourceUuid.set(n.uuid, n.text);
  }
}

function sqlQuote(s: string): string {
  return "'" + s.replace(/'/g, "''") + "'";
}

const now = Date.now();
let emitted = 0;
let skippedMissingText = 0;

process.stdout.write(`-- Generated by scripts/load-suggestions.ts on ${new Date().toISOString()}\n`);
process.stdout.write(`-- Source: db/tag-suggestions-final.jsonl (joined to notes via content_hash)\n`);
process.stdout.write(`-- Idempotent: INSERT OR REPLACE; SELECT skips rows with no matching note.\n\n`);

const lines = readFileSync(FINAL, 'utf8').split('\n');
for (const line of lines) {
  const trimmed = line.trim();
  if (!trimmed) continue;
  const r = JSON.parse(trimmed) as FinalRow;

  const text = textBySourceUuid.get(r.uuid);
  if (!text) {
    // Source uuid not found in newnotes.json — unlikely, but log and skip.
    skippedMissingText++;
    continue;
  }
  const hash = contentHash(text);

  const suggestedTagsJson = JSON.stringify(r.suggested_tags);
  const rationale = r.rationale ?? '';

  // SELECT-form INSERT: if no notes row has this content_hash, zero rows
  // insert (graceful skip, FK safe). If one matches, one row inserts.
  process.stdout.write(
    `INSERT OR REPLACE INTO tag_suggestions ` +
    `(uuid, suggested_tags, primary_tag, confidence, rationale, applied_at, created_at) ` +
    `SELECT n.uuid, ${sqlQuote(suggestedTagsJson)}, ${sqlQuote(r.primary)}, ` +
    `${sqlQuote(r.confidence)}, ${sqlQuote(rationale)}, NULL, ${now} ` +
    `FROM notes n WHERE n.content_hash = ${sqlQuote(hash)};\n`
  );
  emitted++;
}

process.stderr.write(
  `[load-suggestions] emitted ${emitted} INSERT statements, ` +
  `skipped ${skippedMissingText} (source uuid not in newnotes.json)\n`
);
process.stderr.write(
  `[load-suggestions] note: 0 SQL-side rows will land for notes whose content_hash ` +
  `is absent from the notes table (graceful skip via SELECT). ` +
  `Run a post-load SELECT COUNT(*) to confirm.\n`
);
