#!/usr/bin/env tsx
// Deterministic Board Wiki seed.
//
//   tsx scripts/seed-wiki.ts --remote > db/seed.wiki.sql
//   wrangler d1 execute board-db --remote --file=db/seed.wiki.sql
//
// Builds one starter wiki page per top tag. No AI, no background magic.

import { execSync } from 'node:child_process';

const REMOTE = process.argv.includes('--remote');
const TARGET = REMOTE ? '--remote' : '--local';
const limitArg = process.argv.find((arg) => arg.startsWith('--limit='));
const PAGE_LIMIT = limitArg ? Math.max(1, Math.min(100, Number(limitArg.split('=')[1]) || 25)) : 25;
const MIN_NOTES = 3;
const NOW = Date.now();

type NoteRow = { uuid: string; text: string; tags: string; created_at: number; updated_at: number };
type Note = { uuid: string; text: string; tags: string[]; createdAt: number; updatedAt: number };

const rows = fetchRows().map(normalizeNote).filter((note) => note.text.trim());
const groups = groupByTag(rows)
  .filter((group) => group.notes.length >= MIN_NOTES)
  .sort((a, b) => b.notes.length - a.notes.length || a.tag.localeCompare(b.tag))
  .slice(0, PAGE_LIMIT);

process.stdout.write(`-- Generated by scripts/seed-wiki.ts on ${new Date(NOW).toISOString()}\n`);
process.stdout.write(`-- Target: ${TARGET}; source notes: ${rows.length}; pages: ${groups.length}\n`);
process.stdout.write(`-- Idempotent: INSERT OR REPLACE by wiki_pages.slug.\n\n`);

for (const group of groups) {
  const slug = slugify(group.tag);
  const title = titleize(group.tag);
  const sourceRefs = group.notes.slice(0, 12).map((note) => ({
    uuid: note.uuid,
    updatedAt: note.updatedAt,
    excerpt: excerpt(note.text),
  }));
  const relatedSlugs = relatedTags(group.tag, group.notes).slice(0, 8).map(slugify).filter((s) => s && s !== slug);
  const contentMd = pageMarkdown(group.tag, title, group.notes, relatedSlugs);
  const sourceRefsJson = JSON.stringify(sourceRefs);
  const relatedSlugsJson = JSON.stringify(relatedSlugs);
  const summary = `Seeded ${title} from ${group.notes.length} Board notes`;

  process.stdout.write(
    `INSERT OR REPLACE INTO wiki_pages ` +
    `(slug, title, kind, content_md, source_refs_json, related_slugs_json, created_at, updated_at) VALUES (` +
    `${q(slug)}, ${q(title)}, 'topic', ${q(contentMd)}, ${q(sourceRefsJson)}, ${q(relatedSlugsJson)}, ` +
    `COALESCE((SELECT created_at FROM wiki_pages WHERE slug = ${q(slug)}), ${NOW}), ${NOW});\n`
  );
  process.stdout.write(
    `INSERT INTO wiki_events (action, page_slug, source_refs_json, summary, created_at) VALUES (` +
    `'seed', ${q(slug)}, ${q(sourceRefsJson)}, ${q(summary)}, ${NOW});\n`
  );
}

process.stderr.write(`[seed-wiki] emitted ${groups.length} wiki pages from ${rows.length} notes (${TARGET})\n`);
process.stderr.write(`[seed-wiki] top tags: ${groups.slice(0, 10).map((g) => `${g.tag}:${g.notes.length}`).join(', ')}\n`);

function fetchRows(): NoteRow[] {
  process.stderr.write(`[seed-wiki] reading notes from ${REMOTE ? 'remote' : 'local'} D1…\n`);
  const out = execSync(
    `wrangler d1 execute board-db ${TARGET} --json --command "SELECT uuid, text, tags, created_at, updated_at FROM notes ORDER BY updated_at DESC"`,
    { encoding: 'utf8', maxBuffer: 1024 * 1024 * 64 },
  );
  const parsed = JSON.parse(out) as Array<{ results: NoteRow[] }>;
  return parsed[0]?.results ?? [];
}

function normalizeNote(row: NoteRow): Note {
  return {
    uuid: row.uuid,
    text: row.text || '',
    tags: safeTags(row.tags),
    createdAt: Number(row.created_at) || 0,
    updatedAt: Number(row.updated_at) || Number(row.created_at) || 0,
  };
}

function groupByTag(notes: Note[]): Array<{ tag: string; notes: Note[] }> {
  const byTag = new Map<string, Note[]>();
  for (const note of notes) {
    for (const tag of note.tags) {
      if (!tag) continue;
      const list = byTag.get(tag) || [];
      list.push(note);
      byTag.set(tag, list);
    }
  }
  return Array.from(byTag.entries()).map(([tag, ns]) => ({ tag, notes: ns.sort((a, b) => b.updatedAt - a.updatedAt) }));
}

function relatedTags(tag: string, notes: Note[]): string[] {
  const counts = new Map<string, number>();
  for (const note of notes) {
    for (const other of note.tags) {
      if (!other || other === tag) continue;
      counts.set(other, (counts.get(other) || 0) + 1);
    }
  }
  return Array.from(counts.entries()).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0])).map(([t]) => t);
}

function pageMarkdown(tag: string, title: string, notes: Note[], relatedSlugs: string[]): string {
  const newestNote = notes[0];
  const oldestNote = notes.at(-1);
  const latest = newestNote?.updatedAt ? new Date(newestNote.updatedAt).toISOString().slice(0, 10) : 'unknown';
  const oldest = oldestNote?.updatedAt ? new Date(oldestNote.updatedAt).toISOString().slice(0, 10) : 'unknown';
  const examples = notes.slice(0, 8).map((note) => `- ${date(note.updatedAt)} · note:${note.uuid} · ${excerpt(note.text, 180)}`).join('\n');
  const related = relatedSlugs.length ? relatedSlugs.map((slug) => `- [[${slug}]]`).join('\n') : '- None yet.';
  return [
    `# ${title}`,
    '',
    '## Current understanding',
    `This starter page collects ${notes.length} Board notes tagged \`${tag}\`. It is a seeded index, not a finished synthesis.`,
    '',
    '## Shape in the notes',
    `- Latest supporting note: ${latest}`,
    `- Oldest supporting note in this seed: ${oldest}`,
    `- Source count: ${notes.length}`,
    '',
    '## Representative notes',
    examples || '- No representative notes.',
    '',
    '## Related',
    related,
    '',
    '## Open questions',
    '- What should this page claim beyond collecting examples?',
    '- Which notes contradict or refine the current framing?',
  ].join('\n');
}

function safeTags(json: string): string[] {
  try {
    const tags = JSON.parse(json);
    return Array.isArray(tags) ? tags.filter((x): x is string => typeof x === 'string') : [];
  } catch {
    return [];
  }
}

function slugify(s: string): string {
  return s.trim().toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80) || 'untitled';
}

function titleize(s: string): string {
  return s.split(/[\s_-]+/).filter(Boolean).map((part) => part[0]!.toUpperCase() + part.slice(1)).join(' ');
}

function excerpt(text: string, max = 240): string {
  return text.replace(/\s+/g, ' ').trim().slice(0, max);
}

function date(ms: number): string {
  return ms ? new Date(ms).toISOString().slice(0, 10) : 'undated';
}

function q(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}
